version: '3.8'

services:
  db:
    container_name: vecino-vigilante-db
    image: mariadb:11.3-jammy
    volumes:
      - vv-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vecino-vigilante-db
      MYSQL_USER: vv-user
      MYSQL_PASSWORD: vv-password
    restart: always

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080
    restart: always

  api-service:
    container_name: vecino-vigilante-api
    depends_on:
      - db
      - adminer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always

volumes:
  vv-volume:
    external: false